import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {session?.user ? (
          <Timeline />
        ) : (
          <button
            className="rounded-md bg-blue-400 px-10 py-5 text-white shadow-md"
            onClick={() => signIn()}
          >
            Login
          </button>
        )}
      </div>
    </>
  );
};

export default Home;
